name: SBOM CycloneDX and Depedency track
on: push
jobs: 
  syft_dependencytrack:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Syft
        run: curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
  
      - name: Generate SBOM
        run: syft . -o cyclonedx-json > cyclonedx_syft.json
        continue-on-error: true
      
      - name: Post SBOM to Dependency-Track
        run: |
          response=$(curl --location "${{ secrets.API_URL }}" \
          --header "X-Api-Key: ${{ secrets.API_KEY }}" \
          --form "project=${{ secrets.PROJECT_ID }}" \
          --form "bom=@cyclonedx_syft.json")
          echo "Response from curl= $response"
