name: SBOM MS SBOM and Bomber
on: push
jobs: 
  mssbom_bomber:
   runs-on: ubuntu-latest
  
   steps:
      # Step 1: Checkout branch
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: List all files (long listing and hidden)
      - name: List all files
        run: ls -al
  
      # Step 3: Generate SBOM with Syft
      - name: Generate SBOM
        run: |
         curl https://https://github.com/microsoft/sbom-tool/releases/tag/v3.0.1/sbom-tool-linux-x64
         chmod +x sbom-tool
         sbom-tool generate -b ./usr/local/bin -bc .
          

      # Step 4: View the SBOM for confirmation
      - name: View SBOM
        run: cat "spdx_syft.json"

      # Step 5: Install Grype
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Step 6: Scan SBOM with Grype (Table format for quick viewing, no artifact saved)
      - name: Grype Scan - Table Format
        uses: anchore/scan-action@v5
        with:
          sbom: "spdx_syft.json"
          severity-cutoff: "low"
          output-format: table
        continue-on-error: true  # Allows workflow to proceed to the next step even if this one fails

      # Step 7: Scan SBOM with Grype (JSON format and save to file)
      - name: Grype Scan - JSON Format
        run: grype sbom:spdx_syft.json -o json --fail-on low > grype_scan_report.json
        continue-on-error: true

      # Step 8: Upload SBOM and JSON Scan Report as Artifacts
      - name: Upload SBOM and Scan Report as Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Run even if scan fails
        with:
          name: Reports
          path: |
            spdx_syft.json
            grype_scan_report.json
