name: SBOM Syft and Grype
on: push
jobs: 
  syft_grype:
    runs-on: ubuntu-latest
  
    steps:
      # Step 1: Checkout branch
      - name: Checkout
        uses: actions/checkout@v4
  
      # Step 2: Generate SBOM with Syft
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          artifact-name: spdx_syft.json
          output-file: "spdx_syft.json"

      # Step 3: View the SBOM for confirmation
      - name: View SBOM
        run: cat "spdx_syft.json"

      # Step 4: Scan SBOM with Grype (Table format)
      - name: Grype Scan - Table Format
        id: grype_scan_table
        uses: anchore/scan-action@v5
        with:
          sbom: "spdx_syft.json"
          severity-cutoff: "low"
          output-format: table

      # Step 5: Save the Table Format Output
      - name: Save Table Format Output
        if: always() # Run even if scan fails
        run: |
          echo "${{ steps.grype_scan_table.outputs.table }}" > grype_scan_report_table.txt
          cat grype_scan_report_table.txt

      # Step 6: Scan SBOM with Grype (JSON format)
      - name: Grype Scan - JSON Format
        id: grype_scan_json
        uses: anchore/scan-action@v5
        with:
          sbom: "spdx_syft.json"
          severity-cutoff: "low"
          output-format: json

      # Step 7: Save the JSON Format Output
      - name: Save JSON Format Output
        if: always() # Run even if scan fails
        run: |
          echo "${{ steps.grype_scan_json.outputs.json }}" > grype_scan_report.json
          cat grype_scan_report.json
      
      # Step 8: Upload SBOM and Scan Reports as Artifacts
      - name: Upload SBOM and Scan Reports as Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Run even if scan fails
        with:
          name: Reports
          path: |
            spdx_syft.json
            grype_scan_report_table.txt
            grype_scan_report.json
